jumpingintodjango/jumpingintodjango/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'jumpingintodjango.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^login/$','jumpingintodjango.views.login_page',name='login_page'),
	url(r'^logout/$','jumpingintodjango.views.logout_page',name='logout_page'),
	url(r'^$','jumpingintodjango.views.homepage',name='homepage'),
	url(r'^question/$','questionandanwser.views.index',name='index'),
	url(r'^question/details/(?P<q_id>\d+)/$','questionandanwser.views.details',name='details'),
	url(r'^question/createq/$','questionandanwser.views.createForm',name="createForm"),
	url(r'^question/edit/(?P<q_id>\d+)/$','questionandanwser.views.editForm',name='edit'),
    url(r'^admin/', include(admin.site.urls)),
)

jumpingintodjango/questionandanwser/models.py
from django.db import models
from django.utils import timezone

# Create your models here
class Question(models.Model):
	subject = models.CharField(max_length=100)
	description = models.TextField()
	#pub_date = models.DateTimeField()
	pub_date = models.DateTimeField(auto_now_add=True)
	def __unicode__(self):
		return self.subject
	
	def was_published_today(self):
		return self.pub_date.date() == timezone.now().date()
class Anwser(models.Model):
	question = models.ForeignKey(Question)
	content = models.TextField()
	best_anwser = models.BooleanField('is best answer?',default=False)

	def __unicode__(self):
		return self.content

jumpingintodjango/jumpingintodjango/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(max_length=20)
	password = forms.CharField(widget=forms.PasswordInput())

jumpingintodjango/questionandanwser/forms.py
from django import forms
from questionandanwser.models import Question

#class QuestionForm(forms.Form):
#	subject = forms.CharField(required=True,max_length=100)
#	description = forms.CharField(widget=forms.Textarea,required=True)

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		exclude = ('pub_date',)

jumpingintodjango/jumpingintodjango/views.py
from django.shortcuts import render_to_response,redirect
from django.template import RequestContext
from django.contrib.auth import authenticate,login,logout
from jumpingintodjango.forms import LoginForm

def login_page(request):
	message = None
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username,password=password)
			if user is not None:
				if  user.is_active:
					login(request,user)
					return redirect('index')
				else:
					message = "the user is not active"
			else:
				message = "invalid username/password."
	else:
		form = LoginForm()
	return render_to_response('login.html',{"form":form,"message":message},context_instance=RequestContext(request))

def homepage(request):
	return render_to_response('homepage.html',context_instance=RequestContext(request))

def logout_page(request):
	logout(request)
	return redirect('homepage')

jumpingintodjango/questionandanwser/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.utils import timezone
from django.template import RequestContext 
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from questionandanwser.models import Question
from questionandanwser.forms import QuestionForm
# Create your views here.
def index(request):
	question_list = Question.objects.all()
	return render(request,'index.html',{'question_list':question_list})

def details(request,q_id):
	question = get_object_or_404(Question,pk=q_id)
	return render(request,'details.html', {'question':question})

@login_required
def createForm(request):
	if request.method == 'POST':
		form = QuestionForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			subject = cd['subject']
			description = cd['description']
			#q = Question(subject=subject,description=description,pub_date=timezone.now())	
			#q.save()
			form.save()
			return HttpResponseRedirect(reverse('index'))
	else:
		form = QuestionForm()
	return render(request,'createq.html',{'form':form},context_instance=RequestContext(request))
@login_required
def editForm(request,q_id):
	question = get_object_or_404(Question,pk=q_id)
	if request.method == 'POST':
		form = QuestionForm(request.POST,instance=question)
		if form.is_valid():
			cd = form.cleaned_data
			subject = cd['subject']
			description = cd['description']
			#q = Question(subject=subject,description=description,pub_date=timezone.now())
			#q.save()
			form.save()
			return redirect('details',q_id)
	else:
		form = QuestionForm(instance=question)
	return render(request,'editq.html',{'form':form},context_instance=RequestContext(request))

jumpingintodjango/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>JumptoDjango | {% block title %}{% endblock %}</title>
</head>
<body>
<h1>Questions & Anwser | {% block h1 %}{% endblock %}</h1>
{% if user.is_authenticated %}
	<p>Welcome,<b>{{user.username}}.</b><a href="{% url 'logout_page' %}">logout</a></p>
{% else %}
	<p>Welcome,Please<a href="{% url 'login_page' %}">log in</a></p>
{% endif %}
<p><a href="{% url 'homepage' %}">Home</a> | <a href="{% url 'index' %}">Q&A</a></p>
{% block content %}{% endblock %}
{% block footer %}
<hr/>
<p>supported by boring2.</p>
{% endblock %}
</body>
</html>

jumpingintodjango/templates/createq.html
{% extends 'base.html' %}
{% block title %}
create question
{% endblock %}
{% block h1 %}
<span>Create</span>
{% endblock%}
{% block content %}
<form method='post' action=''>
{% include 'form_base.html' %}
<input type="submit" value='Submit'/>
</form>
{% endblock %}

jumpingintodjango/templates/details.html
{% extends 'base.html'%}
{% block title %}
Details
{% endblock %}
{% block h1%}
<span>Details</span>
{% endblock %}
{% block content %}
<h4><a href="{% url 'edit' question.id %}">edit this</a></h4>
<h2>{{ question.subject }}</h2>
<strong>Published:</strong>{{ question.pub_date | date:'D,Y/m/d'}}
{% if question.description %}
	<p>{{ question.description }}</p>
{% else %}
	{% if question.was_published_today %}
		<p>Today.</p>
	{%else%}
		<p>Not Today.</p>
	{%endif%}
<p>no description.</p>
{%endif%}
<h3>Anwser</h3>
{% if question.anwser_set.all %}
	<ul>
	{% for a in question.anwser_set.all %}
		<li>{{a.content|safe}}</li>
	{% endfor %}
	</ul>
{%else%}
<p> no anwser.</p>
{% endif %}
{% endblock %}

jumpingintodjango/templates/editq.html
{% extends 'base.html' %}
{% block title %}
Edit question
{% endblock %}
{% block h1 %}
<span>Edit</span>
{% endblock%}
{% block content %}
<form method='post' action=''>
{% include 'form_base.html' %}
<input type="submit" value='Submit'/>
</form>
{% endblock %}

jumpingintodjango/templates/form_base.html
{% csrf_token %}
{% for f in form %}
{{f.label_tag}}<br/>
{{f.errors}}<br/>
{{f}}<br/>
{% endfor %}

jumpingintodjango/templates/homepage.html
{% extends 'base.html' %}
{% block title %}
Homepage
{% endblock %}
{% block h1 %}
<span>Home</span>
{% endblock%}
{% block content %}
<h3>Welcome this is a homepage.</h3>
{% endblock %}

jumpingintodjango/templates/index.html
{% extends 'base.html' %}
{% block title %}
Index
{% endblock %}
{% block h1 %}
<span>Index</span>
{% endblock%}
{% block content %}
<a href="{% url 'createForm' %}">create question</a>
{% if question_list %}
	{% for q in question_list %}
		<h3><a href="{% url 'details' q.id %}">{{ q.subject }}</a></h3>
	{% endfor %}
{% else %}
	<p>No publish questions.</p>
{% endif %}
{% endblock %}

jumpingintodjango/templates/login.html
{% extends 'base.html' %}
{% block title %}
Login
{% endblock %}
{% block h1 %}
<span>Login</span>
{% endblock%}
{% block content %}
{% if message %}
<p>{{ message }}</p>
{% endif %}
<form method='post' action=''>
{% csrf_token %}
{{form.as_p}}
<input type="submit" value='Submit'/>
</form>
{% endblock %}