myproject/myproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^polls/', include('polls.urls',namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
)

myproject/polls/urls.py
from django.conf.urls import patterns, include, url
from polls import views
urlpatterns = patterns('',
	#url(r'^$', views.index, name='index'),
	#url(r'(?P<poll_id>\d+)/$', views.details, name='details'),
	#url(r'(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'(?P<pk>\d+)/$', views.DetailsView.as_view(), name='details'),
	url(r'(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
	url(r'(?P<pk>\d)/results/$', views.ResultsView.as_view(), name='results'),
)

myproject/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('Date Published')
	def __unicode__(self):
		return self.question
	
	def was_published_recently(self):
		now = timezone.now()
		return now >= self.pub_date >= now - datetime.timedelta(days=1)

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published in one day?'
class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	
	def __unicode__(self):
		return self.choice_text
 

myproject/polls/views.py
from django.shortcuts import render,get_object_or_404
from polls.models import Poll,Choice
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
#from django.http import Http404
# Create your views here.
#def index(request):
#	lastest_polls_list = Poll.objects.order_by('-pub_date')[:5]
#	return render(request,'polls/index.html',{'lastest_polls_list':lastest_polls_list})

#def details(request,poll_id):
	#try:
	#	poll = Poll.objects.get(pk=poll_id)
	#except Poll.DoesNotExist:
	#	raise Http404()
#	poll = get_object_or_404(Poll,pk=poll_id)
#	return render(request,'polls/details.html',{'poll':poll})

#def results(request, poll_id):
#	poll = get_object_or_404(Poll,pk=poll_id)
#	return render(request,'polls/results.html',{'poll':poll})	
class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'lastest_polls_list'
	def get_queryset(self):
		return Poll.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailsView(generic.DetailView):
	template_name = 'polls/details.html'
	model = Poll
	def get_queryset(self):
		return Poll.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	template_name = 'polls/results.html'
	model = Poll
def vote(request, poll_id):
	poll = get_object_or_404(Poll,pk=poll_id)
	try:
		select_choice = poll.choice_set.get(pk=request.POST['selectvote'])
	except KeyError,Choice.DoesNotExist:
		return render(request,'polls/details.html',{'poll':poll,'error_message':'no the choice id'})
	else:
		select_choice.votes += 1
		select_choice.save()
		return HttpResponseRedirect(reverse('polls:results',args=(poll.id,)))

myproject/polls/templates/polls/details.html
<h1>{{ poll.question }}</h1>
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}
{% if poll.choice_set.all %}
	<form action="{% url 'polls:vote' poll.id %}" method="post">
		{% csrf_token %}
		{% for c in poll.choice_set.all %}
			<input type='radio' name='selectvote' value="{{c.id}}" id="choice_{{forloop.counter}}"/>
			<label for='choice_{{ forloop.counter }}'>{{c.choice_text}}</label><br/>
		{% endfor %}
		<input type="submit" value="vote"/>
	</form>
{% else %}
	<p>no choice in it.</p>
{% endif %}

myproject/polls/templates/polls/index.html
{% load staticfiles %}
<link rel='stylesheet' type='text/css' href="{% static 'style.css'%}"/>
{% if lastest_polls_list %}
	<ul>
	{% for poll in lastest_polls_list %}
		<li><a href="{% url 'polls:details' poll.id %}">{{ poll.question }}</a></li>
	{% endfor %}
	</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

myproject/polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>
<ul>
	{% for c in poll.choice_set.all %}
		<li>{{ c.choice_text }} ---- {{ c.votes }}vote{{ c.votes|pluralize }}</li>
	{% endfor %}
</ul>
<a href="{% url 'polls:details' poll.id %}">vote again?</a>